### ISSUE TITLE
[Bug]: Running `examples/colabs/spacy/spaCy_v3_and_W&B_Sweeps.ipynb` raises `CommError: project not found`

### ISSUE THREAD

**Issue by ash0ts** [wandb/examples#136]
### What happened?

When running this [colab](https://colab.research.google.com/github/wandb/examples/blob/master/colabs/spacy/spaCy_v3_and_W%26B_Sweeps.ipynb#scrollTo=3clTHIScSMa6) without any changes I encounter a `CommError`

Trace:
```
ℹ Running workflow 'parameter-search'

==================================== data ====================================
ℹ Skipping 'data': nothing changed

================================ train-search ================================
Running command: /usr/bin/python3 ./scripts/sweeps_using_code.py configs/default_config.cfg training/
404 response executing GraphQL.
{"errors":[{"message":"project not found","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
wandb: ERROR Error while calling W&B API: project not found (<Response [404]>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/internal/internal_api.py", line 147, in execute
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.7/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/internal/internal_api.py", line 141, in execute
    return self.client.execute(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/internal/internal_api.py", line 1849, in upsert_sweep
    raise (e)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/internal/internal_api.py", line 1846, in upsert_sweep
    check_retry_fn=no_retry_4xx,
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/retry.py", line 118, in __call__
    if not check_retry_fn(e):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/internal/internal_api.py", line 1826, in no_retry_4xx
    raise UsageError(body["errors"][0]["message"])
wandb.errors.UsageError: project not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scripts/sweeps_using_code.py", line 48, in <module>
    typer.run(main)
  File "/usr/local/lib/python3.7/dist-packages/typer/main.py", line 864, in run
    app()
  File "/usr/local/lib/python3.7/dist-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "./scripts/sweeps_using_code.py", line 44, in main
    sweep_id = wandb.sweep(sweep_config, project="wandb_spacy_sweeps", entity='wandb')
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_sweep.py", line 103, in sweep
    sweep_id, warnings = api.upsert_sweep(sweep)
  File "/usr/local/lib/python3.7/dist-packages/wandb/apis/internal.py", line 99, in upsert_sweep
    return self.api.upsert_sweep(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/usr/local/lib/python3.7/dist-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/dist-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/internal/internal_api.py", line 1849, in upsert_sweep
    raise (e)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/internal/internal_api.py", line 1846, in upsert_sweep
    check_retry_fn=no_retry_4xx,
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/lib/retry.py", line 118, in __call__
    if not check_retry_fn(e):
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/internal/internal_api.py", line 1826, in no_retry_4xx
    raise UsageError(body["errors"][0]["message"])
wandb.errors.CommError: project not found
```

**Comment by ash0ts** [comment]
`sweep_id = wandb.sweep(sweep_config, project="test-sweeps", entity='wandb')` is the problematic line. We should remove `entity=wandb` or it can't be run as is.

**Comment by tcapelle** [comment]
great! can you make a PR?

**Comment by ash0ts** [comment]
The code the notebook uses is [here](https://github.com/explosion/projects/blob/52a21fb367de392f84c6ceb78d0486ba5d40421d/integrations/wandb/scripts/sweeps_using_code.py#L44) which is maintained by explosion. Would I be fine to raise a PR there?

**Comment by scottire** [comment]
Yes, that'd be fine to open a PR with a fix.

**Comment by svlandeg** [comment]
Merged on our end, so this can be closed :-) Thanks all!
